apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50  # Target average CPU utilization percentage
