apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-auth-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-auth-service
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50  # Target average CPU utilization percentage
