apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: dixitp12/api_gateway:latest
          env:
            - name: USER_AUTH_SERVICE_URL
              value: "http://user-auth-service:3000"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3000"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:3000"
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60  # Increase initial delay to 60 seconds
            periodSeconds: 10
            timeoutSeconds: 5  # Increase timeout to 5 seconds
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
