apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
        - name: init-db
          image: dixitp12/product_service:latest
          command:
            - /bin/sh
            - -c
            - |
              bundle exec rails db:create &&
              bundle exec rails db:migrate
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret
      containers:
        - name: product-service
          image: dixitp12/product_service:latest
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret
          readinessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1028Mi"
              cpu: "500m"
