apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-auth-service
  template:
    metadata:
      labels:
        app: user-auth-service
    spec:
      containers:
        - name: user-auth-service
          image: dixitp12/user_auth_service:latest
          env:
            - name: RAILS_ENV
              value: "development"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: REDIS_URL
              value: "redis://redis:6379/0"
          ports:
            - containerPort: 3000
