apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  RAILS_ENV: "development"
  DATABASE_HOST: "db"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "product_service_development"
  DATABASE_USER: "postgres"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  REDIS_URL: "redis://redis:6379/0"
  USER_AUTH_SERVICE_URL: "http://user-auth-service:3000"
