apiVersion: v1
kind: ConfigMap
metadata:
  name: user-auth-service-config
data:
  RAILS_ENV: "development"
  DATABASE_HOST: "db"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "user_auth_service_development"
  DATABASE_USER: "postgres"